version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "9113:9113"
    command: ["nginx", "-g", "daemon off;"]

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
